spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/room
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
reservation-service:
  base-url: http://localhost:8081/api/reservations
  
server:
  port : 8080